
-- Users Table
create table users (
  id uuid default gen_random_uuid() primary key,
  email text unique not null,
  password text not null,
  name text,
  role text default 'user',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Articles Table
create table articles (
  id bigint generated by default as identity primary key,
  slug text unique,
  title text not null,
  excerpt text,
  content text,
  date date,
  category text,
  category_color text,
  cover_image text,
  status text default 'draft',
  tags text[],
  author_name text,
  author_avatar text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Jobs Table
create table jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  company text not null,
  icon text,
  icon_bg text,
  posted_date date,
  expired_date date,
  salary text,
  description text,
  type text,
  location text,
  category text,
  status text default 'active',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Testimonials Table
create table testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  role text,
  company text,
  avatar text,
  quote text,
  rating integer,
  status text default 'visible',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
