-- Users Table
create table users (
  id uuid default gen_random_uuid() primary key,
  email text unique not null,
  password text not null,
  name text not null,
  role text default 'admin',
  avatar_url text, -- New column for profile picture
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Articles Table
create table articles (
  id bigint generated by default as identity primary key,
  slug text unique,
  title text not null,
  excerpt text,
  content text,
  date date,
  category text,
  category_color text,
  cover_image text,
  status text default 'draft',
  tags text[],
  author_name text,
  author_avatar text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Jobs Table
create table jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  company text not null,
  icon text,
  icon_bg text,
  posted_date date,
  expired_date date,
  salary text,
  description text,
  type text,
  location text,
  category text,
  position text,
  status text default 'active',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Testimonials Table
create table testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  role text,
  company text,
  avatar text,
  quote text,
  rating integer,
  category text,
  status text default 'visible',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Team Table
create table team (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  avatar text,
  bio text,
  email text,
  linkedin text,
  "order" integer default 999,
  status text default 'active',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Portfolio Table
create table portfolio (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text,
  description text,
  image text,
  size text, -- large or medium
  category text,
  technologies text[],
  project_url text,
  github_url text,
  status text default 'draft',
  completed_date date,
  marquee_row text default 'top', -- 'top' or 'bottom'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Partners Table
create table partners (
  id bigint generated by default as identity primary key,
  name text not null,
  logo text,
  website text,
  description text,
  category text,
  status text default 'active',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Site Settings Table
create table site_settings (
  id bigint generated by default as identity primary key,
  key text unique not null,
  value jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
