
-- Team Members Table
create table team (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  avatar text,
  bio text,
  email text,
  linkedin text,
  status text default 'active',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Portfolio Items Table
create table portfolio (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image text,
  category text,
  technologies text[],
  project_url text,
  github_url text,
  status text default 'draft',
  completed_date date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Partners Table
create table partners (
  id bigint generated by default as identity primary key,
  name text not null,
  logo text,
  website text,
  description text,
  category text,
  status text default 'active',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
